---
- hosts: wp_nodes
  become: yes
  vars_files:
    - vars/vars.yaml
  tasks:
    - include_tasks: tasks/os_packages.yaml
    - include_tasks: tasks/db_related.yaml
    - include_tasks: tasks/wp_related.yaml
