- name: "Install EPEL and remirepo" 
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: "Install mariadb repo"
  copy:
    src: files/MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo

- name: "Install httpd"
  yum:
    name: httpd
    state: present

- name: "Install mariadb"
  yum:
    name: 
      - MariaDB-server
      - MariaDB-client
      - MySQL-python
    state: present

- name: "Install php"
  yum:
    name:
      - php80
      - php80-php
      - php80-php-mysqlnd
      - php80-php-pecl-mysql
    state: present
